spring:
    h2:
        console:
            enabled: true
            path: /h2-console
            #localhost:8080/h2-console에서 db확인이 가능
    jpa:
        #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                dialect: org.hibernate.dialect.H2Dialect
    datasource:
        #driver-class-name: com.mysql.cj.jdbc.Driver
        #url: jdbc:mysql://localhost:3306/comento?characterEncoding=utf8
        #username: root
        #password: d201902699
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password:


